### ISSUE TITLE
предлагаю id тоже передавать как аргумент функции, как минимум вначале.

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#13]
предлагаю id тоже передавать как аргумент функции, как минимум вначале.

_Originally posted by @atherdon in https://github.com/LLazyEmail/nomoretogo_email_template/pull/11#discussion_r895061364_

**Comment by atherdon** [comment]
id повторяется и в других компонентах

**Comment by web4uartstudio** [comment]
> id повторяется и в других компонентах

забыл, переделаю
