### ISSUE TITLE
тут лучше делать `export default address`

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#14]
тут лучше делать `export default address`

_Originally posted by @atherdon in https://github.com/LLazyEmail/nomoretogo_email_template/pull/11#discussion_r895061221_

**Comment by atherdon** [comment]
тоже самое сделать и для других компонентов.
также это заденет index.js

**Comment by web4uartstudio** [comment]
забыл сделать для других компонентов, переделаю
