### ISSUE TITLE
добавить иерархию файлов в проекте и кратко описать какой компонент за что отвечает

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#140]
раз мы начинаем путаться в том что происходит с этим простым проектом - значит нам нужна документация

добавьте эту инфу в readme

1. добавить иерархию файлов в проекте - шаблон я добавил
2. кратко описать какой компонент за что отвечает 
формат: название - ссылка на файл - описание

**Comment by web4uartstudio** [comment]
> посмотрите как выглядит: https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/README.md



> посмотрел ваш файл - выглядит круто, но неудобно хранить документ открытым всегда.
> 
> думаю потом эту инфу перенести в readme.
> 
> сегодня было время и мы сделали в readme иерархию по тому шаблону
> 
> посмотрите как выглядит: https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/README.md

👍 👍 👍

**Comment by web4uartstudio** [comment]
> 



> > посмотрите как выглядит: https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/README.md
> 
> 👍 👍 👍
@atherdon

**Comment by web4uartstudio** [comment]
Добрый день. Пишу с телефона. Если сегодня доберусь что то сброшу по
работе. Если нет, тогда завтра продолжу.

пт, 22 июл. 2022 г., 08:37 Arthur Tkachenko ***@***.***>:

**Comment by atherdon** [comment]
гуд - я пока мелкие вещи причесываю

сс @web4uartstudio
