### ISSUE TITLE
move into sub-components

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#179]
**topPanelViewInBrows** into subcomponents/innerTemplate/src/components/topPanelViewInBrows folder

and components here should me moved out too

![image](https://user-images.githubusercontent.com/1469198/180206114-f1751e89-bf6e-41ce-b91a-1eb2e58ab9cc.png)

**Comment by atherdon** [comment]
мы сделали эту задачу? можно ее закрывать?

**Comment by web4uartstudio** [comment]
> мы сделали эту задачу? можно ее закрывать?

Если речь о переносе topPanelViewInBrows - да выполнил, recipeComponent тоже перенесен

**Comment by atherdon** [comment]
а мелкие компоненты, которые например являются частью "внутренностей" для блока контент - их мы перенесли в innerTemplate?

**Comment by web4uartstudio** [comment]
> а мелкие компоненты, которые например являются частью "внутренностей" для блока контент - их мы перенесли в innerTemplate?

да

**Comment by web4uartstudio** [comment]
При переносе/создании в sub,  компонент paragraph не переносил/создавал , там есть вопросы нет универсальности(. Одним словом нужно будет скорее всего возвращаться к вопросу или оставить как есть

**Comment by atherdon** [comment]
закрою этот таск, потому что непонятно что именно нужно делать.
попробуем подойти с другой стороны

**Comment by web4uartstudio** [comment]
> закрою этот таск, потому что непонятно что именно нужно делать. попробуем подойти с другой стороны

 <p style="margin-top: 0px; margin-bottom: 10px; line-height: 150%;"></p>
    ${textTop}
  <p style="margin-top: 0px; margin-bottom: 10px; line-height: 150%;"></p>
  <p style="margin-top: 0px; margin-bottom: 10px; line-height: 150%;"></p>
  <p style="margin-top: 0px; margin-bottom: 10px; line-height: 150%;"><br>
    ${textBottom}
  </p>



один текст стоит между тегами "p" а другой внутри "p". #197 @atherdon

**Comment by atherdon** [comment]
> > закрою этот таск, потому что непонятно что именно нужно делать. попробуем подойти с другой стороны
> 
> ${textTop}
> ${textBottom}
> 
> один текст стоит между тегами "p" а другой внутри "p". #197 @atherdon

ничего непонятно )) дайте ссылку на codeline чтоб я мог посмотреть

**Comment by web4uartstudio** [comment]
Компонент - contentTextDescription
Line 41-47
@atherdon

**Comment by atherdon** [comment]
на гитхабе можно удобно шарить codeline. просто открываете файл на сайте и нажимаете на строку.

[пример](https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/components/supportComponent.js#L32)

сейчас посмотрю

**Comment by atherdon** [comment]
я думаю что это просто баг - скорее всего Стейси использует какой то редактор чтобы работать с темплейтами. и чтото "подвигала" неправильно. давайте просто обернем textTop в <p> и все будет работать

**Comment by web4uartstudio** [comment]
> просто обернем textTop в

я не знаком с тегом "в", как он себя ведет @atherdon

**Comment by web4uartstudio** [comment]
> один текст стоит между тегами "p" а другой внутри "p"

Такой код в оригинальном темлейте

**Comment by atherdon** [comment]
> > просто обернем textTop в
> 
> я не знаком с тегом "в", как он себя ведет @atherdon

я имел ввиду тег **<p>**

**Comment by web4uartstudio** [comment]
Та понял я понял, веселюсь по своему ))

вс, 31 июл. 2022 г., 23:19 Arthur Tkachenko ***@***.***>:

**Comment by web4uartstudio** [comment]
В последнее время участились случаи git bugs, не знаю с чем связано. И sync
стараюсь делать до, вовремя и после

вс, 31 июл. 2022 г., 23:20 WEB 4 YOU ***@***.***>:

**Comment by atherdon** [comment]
самый простой вариант:
1.когда начинаете работать нужно сделать sync и полностью рестартануть проект. 
т.к. я использую gitpod(cloud ide) - у меня всегда заново устанавливаются пакеты и идет build. 
т.к. несколько раз ваши изменения крешили основной install - предполагаю что или sync или npm install можете пропускать.

2. даже у себя в репозитории вы можете использовать так называемые feature branches. они обычно одноразовые и нужны для того чтобы например пофиксить баг и сделать PR. отдельные ветки могут помочь.

любой merge conflict означает что sync не был произведет.


Плюс если у вас локальная IDE - возможно вы делаете sync на гитхабе но не делаете pull на вашу локальную машину.

**Comment by atherdon** [comment]
я пытаюсь следить, поэтому вдруг что - подхвачу вас.

кстати - может вам дать купоны на мои курсы по гиту?

**Comment by web4uartstudio** [comment]
> кстати - может вам дать купоны на мои курсы по гиту?

У Вас кстати купонов на время(добавочное в сутках) случайно нет ? Оооооочень надо.
Буду благодарен за купоны. Я до сих пор линекдин не могу добить (((((((((((((((((( @atherdon

**Comment by atherdon** [comment]
такого нету и незнаю что посоветовать

первые два курса
- https://www.udemy.com/course/git-basics-and-merging-process/?couponCode=B6FEEAB79D78EF5C3FE2
- https://www.udemy.com/course/git-workflows-in-depth/?couponCode=2ECB872FCD6241B42403

насчет линкедина - я бы разбивал задачу на мелкие части. или пытался подготовить информацию пока я не сижу за компьютером а потом просто вводить ее с листика
