### ISSUE TITLE
images

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#190]
https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/twitter.webp
https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/amazon.png
https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/facebook.webp
https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/instagram.webp
https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/logo.jpeg

https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/recipe1.jpeg
https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/recipe2.jpeg
https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/recipe3.jpeg

https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/recipe4.jpeg
https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/recipe5.jpeg
https://raw.githubusercontent.com/LLazyEmail/nomoretogo_email_template/main/data/images/recipe6.jpeg

**Comment by atherdon** [comment]
html file: https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/data/startTemplate.html

**Comment by atherdon** [comment]
1 перенос ссылок в html
2. скопирировать ссылки в readme
3. заменить fake data ссылками

**Comment by atherdon** [comment]
https://user-images.githubusercontent.com/1469198/180625411-f9e8e1f7-1b03-4bef-8480-c5e1770eead6.mp4

**Comment by atherdon** [comment]
cc @Olgalex

**Comment by Olgalex** [comment]
Эти 11 ссылок заменены в файле. Пулл отправила)

**Comment by atherdon** [comment]
дякую - тогда следующий шаг это readme а потом приступим к интересному

**Comment by atherdon** [comment]
задача 3.1 поставить ссылки на картинки с рецептами в эти переменные(ссылка пойдет внутрь строки)

https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/display/displayContent.js#L84

`    src: '123',`

**Comment by atherdon** [comment]
3.2 названия рецептов, которые у нас [в этой задаче](https://github.com/LLazyEmail/nomoretogo_email_template/issues/194) мы поставим в 

https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/display/displayContent.js#L87

`    title: '123',`

**Comment by Olgalex** [comment]
one more task is ready

**Comment by atherdon** [comment]
looks good, but please dont forget about syncing your repo.

i also added a comment about `href` attribute: https://github.com/LLazyEmail/nomoretogo_email_template/pull/196#discussion_r929009949

---

please proceed with 3.2

**Comment by atherdon** [comment]
done
