### ISSUE TITLE
migration of small components

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#197]
в typography у нас сейчас мало компонентов. А Вадим хочет попробывать работу этого модуля и подклюить его к основному генератору.

я создал пустые файлы, если будут вопросы -скажите, я детальнее сделаю описание.

вначале надо перенести: 
- image

- heading - там где **Weekly Menu**
![image](https://user-images.githubusercontent.com/1469198/180827517-63b945c7-0215-41c7-a7a1-5d7521fe433a.png)

---

- subheading
![image](https://user-images.githubusercontent.com/1469198/180827555-972da0cd-84d6-406b-95c3-aae75360aa05.png)

---

- paragraph
![image](https://user-images.githubusercontent.com/1469198/180827591-28046adb-cb22-4334-a5b1-6d1d22cefe47.png)

---

- strong

![image](https://user-images.githubusercontent.com/1469198/180827704-e67d8e22-79d3-4424-bb8d-ece5413a8990.png)

---

**Comment by atherdon** [comment]
нашел пример для link & strong
supportComponent.js:
- createSupportLink
- createSupportTitle

**Comment by atherdon** [comment]
я вчера посмотрел компоненты, там heading выглядит как ссылка - в темлпейте там тоже ссылка?
я думал что там просто h1-h2...

**Comment by web4uartstudio** [comment]
> я вчера посмотрел компоненты, там heading выглядит как ссылка - в темлпейте там тоже ссылка?
> я думал что там просто h1-h2...

Да, является ссылкой

**Comment by atherdon** [comment]
тогда закрываю
