### ISSUE TITLE
footer content

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#199]
для href мы закинем строки с этими ссылками
1. https://www.facebook.com/nomoretogo/
2. https://www.twitter.com/nomoretogo
3. https://www.instagram.com/nomoretogo

а src для картинок мы возьмем из [нашего readme](https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/README.md#static-images) и картинок которые вы добавляли

сс @Olgalex

**Comment by Olgalex** [comment]
Ready
