### ISSUE TITLE
i run npm install in our root and get this error

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#215]
![image](https://user-images.githubusercontent.com/1469198/181355765-3c390f1a-57c4-4ccf-ad84-155e26019b63.png)

**Comment by atherdon** [comment]
#214

**Comment by web4uartstudio** [comment]
Вчера получил bugs от git (долго не мог pull сделать в итоге) скорее всего с этим было связано, попробуйте еще раз @atherdon

**Comment by atherdon** [comment]
понял. посмотрю когда буду делать update подмодулей

**Comment by atherdon** [comment]
спасибо

**Comment by atherdon** [comment]
done
