### ISSUE TITLE
inner template install error

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#245]
![image](https://user-images.githubusercontent.com/1469198/182029355-dba80d73-bfe0-43b9-99fc-5ae0a46039f4.png)

**Comment by atherdon** [comment]
i fixed it, sorry for bothering

**Comment by web4uartstudio** [comment]
Я сижу тоже над этим, я так понимаю что ошибки возникают если :
1 Не обновленные компоненты
2 Импорты не корректные
3 Еще после git bugs

На момент последнего пулл (который собирал весь шаблон у меня выводилось все большое полотно, ошибок не было я проверял перед отправкой )

Ок. я сейчас постараюсь вернуть назад все то что успел редактировать.

Тогда вопрос: где сейчас лезет error ? @atherdon
