### ISSUE TITLE
sub-components

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#255]
## supportComponent.js

Точно можно перенести этот файл в outerTemplate (я же правильно понимаю что этот блок является статическим и не будет меняться?)

### [createSupportLink](https://github.com/LLazyEmail/nomoretogo_email_template/blob/58b84e027e6c461ff8f769a951fbb5233fc0eb8d/src/components/supportComponent.js#L11)
![image](https://user-images.githubusercontent.com/1469198/182038048-f038681b-325d-4909-bff0-4f2e41b0e940.png)

уже есть todo чтобы заменить ссылку на компонент.

### [createSupportMail](https://github.com/LLazyEmail/nomoretogo_email_template/blob/58b84e027e6c461ff8f769a951fbb5233fc0eb8d/src/components/supportComponent.js#L63)

![image](https://user-images.githubusercontent.com/1469198/182038270-0161ec66-3473-46fb-8f1b-806d028c7087.png)

тоже можно обновить/упростить и заодно потестируем работу linkComponent

**Comment by atherdon** [comment]
can i close this task?

**Comment by web4uartstudio** [comment]
> can i close this task?

yes
