### ISSUE TITLE
header logo + staticContentComponent + Button 2

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#317]
https://user-images.githubusercontent.com/1469198/183288558-49248f38-2ff2-4391-a5b4-94a484c7d6f0.mp4

**Comment by atherdon** [comment]
did we complete it, right?

**Comment by web4uartstudio** [comment]
> did we complete it, right?

Да, но 'stringify-attributes' мне не удалось запустить. Остальное ok @atherdon

**Comment by atherdon** [comment]
тогда таск закрою. а со stringify мы возможно с другой стороны подойдем.

я думаю что мы можем сделать отдельный модуль typography внутри которого будет stringify-attributes и мы создадим там базовые компоненты которые могут работать как в hn темплейте, так и в nmtg
