### ISSUE TITLE
i run `yarn test:write` and get this error

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#324]
![image](https://user-images.githubusercontent.com/1469198/184721283-ddcea13b-b672-4e1a-b859-951b5f63d7f2.png)

**Comment by web4uartstudio** [comment]
Это не мои правки. Точно @atherdon 
Посмотрю

Как ситуация в городе? новости не очень ((((

**Comment by atherdon** [comment]
да, посмотрите плз, потому что я пока отдыхаю от кода.

ну русня уже 2-3 недели постоянно обстреливает рядом со мной. я уже начать спать днем, потому что это невозможно
