### ISSUE TITLE
сделать компонент content

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#34]
пока не начинать. нужно описание.

логика этого компонента простая. есть внешний темлпейт, который не особо меняется. header, footer и т.д. эта часть практически статическая. а есть внутренняя часть, которая меняется каждую неделю на проекте nmtg. 

и внутренняя часть будет нуждаться в качественном коде и постоянно будет обновлятся/улучшаться/тестироваться. 

в этот компонент будут входить блоки на скрине

![image](https://user-images.githubusercontent.com/1469198/173240634-35f2fb88-ce32-4844-8baa-784d85d3710a.png)

**Comment by atherdon** [comment]
посути это компонент враппер, в который мы засунем много мелких компонентов которые есть у нас, для того чтобы наш темплейт работал.

для recipe-component мне ненужен цикл, вы можете просто вызвать 6 раз функцию и передать туда данные.
желательно сразу сделать так, чтобы было удобно и красиво. специально не говорю деталей, чтобы подумали, посмотрели как делалось в других файлах

**Comment by web4uartstudio** [comment]
Попробовал

ср, 15 июн. 2022 г., 00:05 Arthur Tkachenko ***@***.***>:
