### ISSUE TITLE
recipe component

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#35]
тут у нас функция состоит из нескольких компонентов

![image](https://user-images.githubusercontent.com/1469198/173240878-07ef3ea8-7a6c-46f0-96d3-206817d57be7.png)

**Comment by atherdon** [comment]
@web4uartstudio эта задача готова?

**Comment by web4uartstudio** [comment]
Да

чт, 16 июн. 2022 г., 01:55 Arthur Tkachenko ***@***.***>:
