### ISSUE TITLE
нужно делать sync чаще

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#51]
![image](https://user-images.githubusercontent.com/1469198/173552940-a1290d3b-b6da-465a-a808-2e953ba50f41.png)

**Comment by web4uartstudio** [comment]
Добрый день. Сообщения вижу через телефон. Сегодня начну чуть с
запозданием. (Если это сообщение вообще дойдет). Для информации

вт, 14 июн. 2022 г., 13:10 Arthur Tkachenko ***@***.***>:

**Comment by atherdon** [comment]
специально добавлю изменений в main repo чтобы в новом пулл-реквесте начались конфликты
