### ISSUE TITLE
общий таск

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#6]
- посмотреть #2, #3, #4
- сделать #1

темплейт я перенес в корень репозитория сейчас.

- потом задача #5.

Я вечером сделаю детальное описание, но для начала информации достаточно

**Comment by atherdon** [comment]
переписку давайте вести на гитхабе, чтоб быстрее отвечать

**Comment by web4uartstudio** [comment]
Что предлагаю я как вариант:

1. Взять/разработать шаблон для письма

2. Разбить на функции (генерация составляющих блоков)



Получаем на вход данные, генерируем Template с данными.



Я когда то делал подобный функционал на PHP.  Для отправки по email

**Comment by atherdon** [comment]
Темплейт который будет подходить под все кейсы очень сложно сделать.
У нас есть один пустой темплейт на примете, но вначале мы хотим добить
текущие задачи и обкатать генератор.

В этом темплейте много лишнего, там 3 тыщм строк. Но как test case он хорош

вт, 7 июн. 2022 г., 11:06 PM web4uartstudio ***@***.***>:

**Comment by web4uartstudio** [comment]
Я нашел +- готовый темплейт, разобью сформирую сброшу

**Comment by web4uartstudio** [comment]
https://drive.google.com/file/d/1tioBV7LvsdMOFmQAOoDEnEX1HlJyOwv0/view?usp=sharing

**Comment by web4uartstudio** [comment]
Файлы находятся - src/my-test-project/
Файл с данными - src/my-test-project/inData/inData.js

Как работает:
Данные считываются с файла inData.js - вставляются в шаблон

Как посмотреть сгенерированный файл:
Подключить фаил dist//index.es.js в HTML
<body>
    <script type="module">
      import output from "./index.es.js";
      document.body.innerHTML = output;
      console.log(output);
    </script>
  </body>

**Comment by web4uartstudio** [comment]
В консоли можно забрать весь код темплета

**Comment by web4uartstudio** [comment]
Данные inData:
1 header - фото для header
2 main - заголовок и описание (основные)
3 content - заголовок и описание для блока контента а также данные для блока с фотографиями(ссылка на фото, линк к фото, описание к фото)

**Comment by web4uartstudio** [comment]
Если на правильном пути то в последующем можно добавить линки на соц. сети

**Comment by atherdon** [comment]
@web4uartstudio сейчас посмотрю. если вы сделали также как я показал на примере - тогда думаю правильно.

давайте утвердим условия на фриланс ханте, чтоб я мог деньги в сейф положить.

**Comment by atherdon** [comment]
а вы с гитхабом раньше не работали? @web4uartstudio

**Comment by atherdon** [comment]
< Я не знаю сколько это стоит и не уверен что все сделал правильно.

моя задача попробывать ввести вас в проект и с вашей помощью сделать некоторые мелкие задачи. Плюс, т.к. я все равно буду тратить тут время с вами - я параллельно обновлю некоторые методы, которые раньше не работали, добавлю тесты и т.д. - что хорошо для проекта в целом.

без стоимости я не понимаю как вас оценить. 

задач мелких у нас много, можно делать проект будет долго, при этом у нас пока нету клиента для этого проекта, который бы использовал генератор и платил - поэтому мы ищем начинающего дева, который бы мог двигать немного проект вперед.

**Comment by atherdon** [comment]
еще небольшое дополнение: вы ваш код из `dist` подключали в html - мы так не делаем. 
по сути, мы делаем npm модуль/модули, которые потом будут установленны в markdown-to-email(если техлид разрешит) и будут использоваться на серверной стороне.

тестировать вначале эти функции не получится. я специально сделал проект `trying_lit` таким образом, чтобы все лишнее там отсечь. 

при этом, мы попробуем потом покрыть модуль тестами, чтобы понимать работает он или нет раньше чем начнем подключать его в markdown-to-email

**Comment by atherdon** [comment]
нашел несколько видео по гитхабу, сорри что русские.
можете посомтреть как будет время, лишним не будет

- https://www.youtube.com/watch?v=zZBiln_2FhM
- https://www.youtube.com/watch?v=hyUBMmL0WtA
- https://www.youtube.com/watch?v=fYFiQ7lpfiE

**Comment by web4uartstudio** [comment]
Мне нужна помощь на предмет правильно ли я понимаю:
1. Беру - https://github.com/LLazyEmail/nomoretogo_email_template
2. Разбиваю его на составные части путем function - > return
4. Переименовую темплейт.
5. Работа добавляется сразу в github (видео посмотрю спасибо) 

Я не туплю, я учусь работать в команде по ТЗ))

**Comment by atherdon** [comment]
0. нам всетаки нужно понять стоимость вашего часа работы и залить на сейф оплату за 10 часов. 
1. из репозитория https://github.com/LLazyEmail/nomoretogo_email_template вы берете темлпейт от моей старой клиентки.
2. вначале переносите функции, как 
```

const spacer = function () {
  return '<div class="spacer" style=" line-height: 40px; height: 40px; mso-line-height-rule: exactly; ">&nbsp;</div>';
};


const MainTitleText = function (main) {
  return (
    '<tr><td style="padding: 10px; text-align: left"><h1 style="margin-top: 0;margin-bottom: 16px;font-family: Arial, sans-serif;font-size: 26px;line-height: 32px;font-weight: bold;">' +
    main.title +
    '</h1><pstyle="margin: 0;font-family: Arial, sans-serif;font-size: 18px;line-height: 24px;">' +
    main.description +
    "</p> </td></tr>"
  );
};


``` 
в этот репозиторий, чтобы мы не потеряли этот код.
2.1 разбиваете не весь темплейт, а вытаскиваете только те элементы, которые указаны в задаче #5. если будут вопросы - в том таске вы можете их задать и я добавлю описание.

3. темлпейт можно переименовать сразу, заодно обкатаем с вами работу с гитхабом.

4. я записал несколько курсов по гиту на английском. могу скинуть бесплатные купоны. там на самом деле много полезного можно делать.

> Я не туплю, я учусь работать в команде по ТЗ))

я так даже не думал. чтоб войти в проект который уже более года делается - нужно время. поэтому я и придумал это задание. возможно когда мы доделаем этот темплейт, добавим тесты и улучшим логику генерации темплейта - основной проект тоже пойдет быстрее.

Плюс, это хорошее место для командной работы и обучения. например если мы сможем поработать несколько месяцев - для ваших скиллов это будет очень выгодно. мы ж используем best practices которые девы используют на международном уровне

**Comment by atherdon** [comment]
нашел украинца с курсами

https://www.youtube.com/watch?v=O00FTZDxD0o

**Comment by atherdon** [comment]
есть еще и статья о том зачем темплейт разбивать на такие части

https://hackernoon.com/organizing-an-advanced-structure-for-html-email-template

**Comment by web4uartstudio** [comment]
Касательно оплаты: я готов обговорить сумму, предложите если у вас есть опыт подобных работ. Что бы я мог ориентироваться что мне за это светит).

**Comment by atherdon** [comment]
> Касательно оплаты: я готов обговорить сумму, предложите если у вас есть опыт подобных работ. Что бы я мог ориентироваться что мне за это светит).

Мы обсудили это с Вадимом. Мы сейчас готовы платить 60грн за час по таким задачам. Это не много, но зато можно будет брать количеством. Думаю что часов 30 ваших мы в этом модуле точно потратим, до того момента как что-то заработает как нужно.

Завтра вечером смогу собрать ещё один таск, чтобы вы могли делать и я вас не тормозил.

cc @web4uartstudio

**Comment by atherdon** [comment]
добавлю вас в этот репозиторий как contributor, чтобы проще было на вас таски кидать

**Comment by web4uartstudio** [comment]
> Мы обсудили это с Вадимом. Мы сейчас готовы платить 60грн за час по таким задачам. Это не много, но зато можно будет брать количеством. Думаю что часов 30 ваших мы в этом модуле точно потратим, до того момента как что-то заработает как нужно.

Доброго дня. Согласен давайте попробуем. И что делать с freelancehunt, висит задача. Мне подтвердить или будут корректировки ?

**Comment by atherdon** [comment]
@web4uartstudio обновили условия на freelancehunt. как примете, добавим оплату в Сейф.

сейчас добавлю новых задач

**Comment by atherdon** [comment]
Мы обсудили это с Вадимом. Мы сейчас готовы платить 60грн за час по таким
задачам. Это не много, но зато можно будет брать количеством. Думаю что
часов 30 ваших мы в этом модуле точно потратим, до того момента как что-то
заработает как нужно.

Завтра вечером смогу собрать ещё один таск, чтобы вы могли делать и я вас
не тормозил.
