### ISSUE TITLE
we need to create separate index.js files for each type of components

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#61]
... and import/export those components via new "index" files

- typography/src/index.js
- misc..../src/index.js
- innerTemplate/src/index.js

**Comment by web4uartstudio** [comment]
> * innerTemplate/src/index.js

не нашел

**Comment by atherdon** [comment]
так их нужно создать )) я просто путь указал где эти файлы будут находится

**Comment by web4uartstudio** [comment]
> так их нужно создать )) я просто путь указал где эти файлы будут находится

не совсем со мной так плохо). Я понял/воспринял что нужно создать index файл в папках назначения.
Но если папки typography и miscellaneous существуют и в них добавлены index, то innerTemplate - нет. Соответственно и вопрос возник. В корне создавать или ?

**Comment by atherdon** [comment]
папку закинуть туда же, где typography

**Comment by web4uartstudio** [comment]
> папку закинуть туда же, где typography

1. папку и фаил innerTemplate/src/index.js - создал
2. папку и фаил miscellaneous/src/index -тоже

**Comment by web4uartstudio** [comment]
Если правильyо понял то данное действие в PR https://github.com/LLazyEmail/nomoretogo_email_template/pull/71
