### ISSUE TITLE
best practices for error handling

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#63]
read a few of those articles, it might help you with cases, like this one: https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/components/tableWithTwoRecipes.js#L72

- https://betterprogramming.pub/javascript-clean-code-error-handling-9cd7e87fdbe3
- https://iaincollins.medium.com/error-handling-in-javascript-a6172ccdf9af
- https://blog.appsignal.com/2021/11/03/designing-error-messages-and-a-logging-strategy-in-nodejs.html
- https://www.valentinog.com/blog/error/

**Comment by atherdon** [comment]
а можете показать где это было сделано

**Comment by atherdon** [comment]
> По данному заданию не совсем тогда понятно что требуется, Сделать исключения try, catch или написать общий фаил по ошибкам или пойти почитать еще раз ?

вопрос сложный. для простых компонентов нам достаточно просто throw new error.
а вот со сложными компонентами - у нас явно перегружена логика. не очень удобно работает сейчас

**Comment by atherdon** [comment]
Мне нужно расписать детально что мы можем сделать лучше

**Comment by web4uartstudio** [comment]
Если можно то да. Я сегодня сделал пробный вариант в количестве 1шт, он был принят. По этому и решил что заходит. Переделал остальные. Или на что обратить внимание и что допилить

**Comment by atherdon** [comment]
@web4uartstudio все гуд.
текущий вариант работает, но я хочу найти an option который я смогу размножить на 3 репозитория/ тут просто задача в том что надо усидеть на нескольких стулях

**Comment by atherdon** [comment]
https://github.com/LLazyEmail/nomoretogo_email_template/pull/99#issuecomment-1164912476

**Comment by web4uartstudio** [comment]
>перечислить список компонентов, внутри которых у нас есть массив с error messages?
1. Компоненты которые содержат более двух  error messages - tableWithTwoRecipes, get-recipe, get-supportContact

**Comment by atherdon** [comment]
1. [tableWithTwoRecipes](https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/components/tableWithTwoRecipes.js)
2. [get-recipe.js](https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/components/get-recipe.js)
3. [get-supportContact.js](https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/components/get-supportContact.js)

**Comment by atherdon** [comment]
### [tableWithTwoRecipes](https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/components/tableWithTwoRecipes.js)
1. простое улучшение может быть в том, что мы передаем не 6 аттрибутов а например 2 объекта.
2. https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/components/tableWithTwoRecipes.js#L72-L88
эта функция не очень "читабельна". я бы не экспортировал таким образом.
мы прийдем к тому, что наши компоненты будут собраться вместе в файлах display/display-* и там мы наверное будем передавать данные и вызывать функции. 

я бы скорее назвал эту функцию как то, аля checking for errors, а кспортировал бы только компонент.

можете посмотреть как я начал делать футер в репозитории https://github.com/LLazyEmail/_trying-lit/blob/main/src/components/footer.js

это не конечный вариант, но позволят легко читать как работают некоторые блоки в теплейте.

**Comment by atherdon** [comment]
### [get-supportContact.js](https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/components/get-supportContact.js)

предлагаю сделать похожие шаги как я указал выше, а потом уже по-факту посмотрю еще раз

**Comment by atherdon** [comment]
#102

**Comment by atherdon** [comment]
закрою таск, т.к. мы переносим всю информацию в репозиторий documentation
