### ISSUE TITLE
папка components/outerTemplate/src/components

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#64]
1. вынести эту папку в root/components/*
2. после создания index внутри этой папки, нужно перенести туда такие файлы как
- headComponent
- footerComponent(да, давайте переименуем)
- bodyComponent(что будем делать?)
- давайте объединим файлы font в один файл и вернем просто 2 функции

3. все компоненты, которые находятся в папке надо будет перенести в `outerTemplate/src/components`

4. т.к. у нас теперь есть несколько файлов index - нам не обязательно в этом файле подключать каждый компонент отдельно. мы можем сделать import всех компонентов сразу из того index файла. переделайте пожалуйста.

https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/index.js#L16-L20

5, вынести модуль outerTemplate из нашего другого модуля, чтобы они не пересекались. при этом конечно прийдется поменять кучу путей.

**Comment by web4uartstudio** [comment]
> 1. вынести эту папку в root/components/*
1. Создать :root/components/outerTemplate/src/component/
2. Перенести из :root/src/components такие компоненты как : headComponent, footerComponen(да, переименовал), bodyComponent(будем считать что он у нас есть, хотя может о нем забыть как о страшном сне)) )





> 3\. все компоненты, которые находятся в папке надо будет перенести в `outerTemplate/src/components`

1. Переносим из :root/src/outerTamplate все файлы

> вынести модуль outerTemplate из нашего другого модуля, чтобы они не пересекались. при этом конечно прийдется поменять кучу путей.

понял но не понял

**Comment by atherdon** [comment]
< будем считать что он у нас есть, хотя может о нем забыть как о страшном сне))

я не видел чтоб у нас был такой компонент сейчас. я просто пытаюсь привести все наши компоненты к логике, которая у нас в репозитории https://github.com/LLazyEmail/_trying-lit

**Comment by atherdon** [comment]
> понял но не понял

хочу сейчас все модули держать в https://github.com/LLazyEmail/nomoretogo_email_template/tree/main/components

**Comment by web4uartstudio** [comment]
1. Мои рассуждения по 1,3 пункту верны ?
2. 5 пункт чуть запутанно, не хочется с 5 дубля прийти к нужному результату. Можно чуть развернуть что, откуда и куда. 
про пути все понятно

**Comment by web4uartstudio** [comment]
> я не видел чтоб у нас был такой компонент сейчас.

Вот он https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/src/components/get-body.js родненький)

**Comment by atherdon** [comment]
Рассуждения верны

Название файла можно переименовать.

Мы все равно будем переделывать несколько раз, так или иначе. Потому что я
планирую новые фишки добавлять, а как они будут работать, пока не ясно
