### ISSUE TITLE
we can move it away

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/nomoretogo_email_template#65]
we can move it away

_Originally posted by @atherdon in https://github.com/LLazyEmail/nomoretogo_email_template/pull/57#discussion_r898123191_

**Comment by web4uartstudio** [comment]
> давайте создадим общую оболочку. это сложно?
Ну судя по всему она теперь есть "contentMainTableWrap.js" в PR https://github.com/LLazyEmail/nomoretogo_email_template/pull/71

**Comment by atherdon** [comment]
@web4uartstudio давайте перенесем "contentMainTableWrap.js" в innerTemplate
